### ISSUE TITLE
#環境構築

### ISSUE THREAD

**Issue by kinaru0227** [banarsbaseball/home_page#10]
環境開発構築手順4の画像の
「Gitリポジトリのクローン…」っていうリンクないよ
調べてショートカットから検索して出す方法試したけど、なんかうまくいかなかった
visual studio codeのバージョンの問題なんだろうかね
![image](https://user-images.githubusercontent.com/116728270/202836214-06ea7792-dc18-43fa-9335-c5fcb4d5277f.png)

**Comment by banarsbaseball** [comment]
環境構築が完了したのでクローズ
